name: 'VirtualBox'
description: 'Run CI in VirtualBox for GitHub Actions'
inputs:
  box:
    description: 'the vagrant box name'
    required: true
  run:
    description: 'the commands to run in vm'
    required: true
  mem:
    description: 'the memory size of the vm'
    required: false
    default: '2048'
branding:
  icon: 'activity'  
  color: 'green'

runs:
  using: 'composite'
  steps:
  - run: |
      WORK_DIR=$(mktemp -d)
      cd "$WORK_DIR"

      echo 'set -e' > shell.sh
      echo "cd /home/vagrant/${GITHUB_REPOSITORY}" >> shell.sh
      cat >> shell.sh <<'EOF'
      ${{inputs.run}}
      EOF

      chmod a+x shell.sh
      
      cat > Vagrantfile <<EOF
        Vagrant.configure("2") do |config|
          config.vm.box = "${{inputs.box}}"
          config.vm.provider "virtualbox" do |vb|
            vb.memory = "${{inputs.mem}}"
          end
          config.vm.synced_folder "${GITHUB_WORKSPACE}", "/home/vagrant/${GITHUB_REPOSITORY}", type: "rsync"
          config.vm.provision "shell", path: shell.sh
        end
      EOF

      run() {
        printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
        $@
      }

      run cat Vagrantfile
      run cat shell.sh
      run vagrant box add ${{inputs.box}}
      run vagrant up
      run vagrant provision
    shell: bash 
